-- DROP ALL TABLE
DROP TABLE BOARD_FILE;
DROP TABLE BOARD;
DROP TABLE TRANSACTION_DETAIL;
DROP TABLE CONNECTED_ACCT;
DROP TABLE ACCOUNT;
DROP TABLE MEMBER;
DROP TABLE COMM_CODE;
DROP TABLE COMM_CODE_CLASS;
DROP TABLE EXCEPTION_LOG;

-- TABLE 생성
@EXCEPTION_LOG 'SCOTT.';
@COMM_CODE_CLASS 'SCOTT.';
@COMM_CODE 'SCOTT.';
@MEMBER 'SCOTT.';
@ACCOUNT 'SCOTT.';
@CONNECTED_ACCT 'SCOTT.';
@TRANSACTION_DETAIL 'SCOTT.';
@BOARD 'SCOTT.';
@BOARD_FILE 'SCOTT.';

COMMIT;


-- SELECT
SELECT * FROM COMM_CODE_CLASS;
SELECT * FROM COMM_CODE;
SELECT * FROM MEMBER;
SELECT * FROM ACCOUNT;
SELECT * FROM CONNECTED_ACCT;
SELECT * FROM BOARD;
SELECT * FROM BOARD_FILE;

-- USER OBJECT 확인
--SELECT * FROM USER_SEQUENCES
--SELECT * FROM USER_CONSTRAINTS;
--SELECT * FROM USER_TABLES;


commit;