REM ***********************************************************************************************
REM SCRIPT 용도   : BOARD(게시글) 테이블 생성 및 데이터 삽입
REM 작성자         : 서유경
REM 작성일         : 2022-07-12, Version 1
REM 수정일
REM
REM 주의사항       : 1. DBA 권한을 가진 사용자로 테이블을 생성할 것
REM
REM 수정사항 FORMAT     YYYY-MM-DD  수정자 수정내용
REM 수정사항
REM ***********************************************************************************************

DROP TABLE &1.BOARD;
DROP SEQUENCE &1.SEQ_BOARD;

CREATE TABLE &1.BOARD(
    BOARD_SEQ       NUMBER(10)      CONSTRAINT PK_BOARD PRIMARY KEY,
    BOARD_TYPE      NUMBER(3)       NOT NULL,
    SUPER_BOARD_SEQ NUMBER(10),
    TAB_CNT         NUMBER(10)      DEFAULT 0,
    WRITER          VARCHAR2(50)    NOT NULL,
    TITLE           VARCHAR2(100),
    CONTENT         VARCHAR2(4000),
    VIEW_CNT        NUMBER(5)       DEFAULT 0,
    REG_DATE        DATE            DEFAULT SYSDATE,
    CONSTRAINT FK_BOARD_BOARD_SUPER_BOARD_SEQ FOREIGN KEY(SUPER_BOARD_SEQ) 
        REFERENCES &1.BOARD(BOARD_SEQ),
    CONSTRAINT FK_BOARD_MEMBER_WRITER FOREIGN KEY(WRITER) 
        REFERENCES &1.MEMBER(ID)  
);

CREATE SEQUENCE &1.SEQ_BOARD
    INCREMENT BY    1
    START WITH      0
    MAXVALUE        9999999999
    MINVALUE        0
    NOCYCLE
    NOCACHE;


INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '2348589747', '1번 질문입니다.', '1번 질문 내용입니다.', '2022-03-01');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '2348985393', '2번 질문입니다.', '2번 질문 내용입니다.', '2022-03-02');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, 'sk', '3번 질문입니다.', '3번 질문 내용입니다.', '2022-03-03');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '2348985393', '4번 질문입니다.', '4번 질문 내용입니다.', '2022-03-04');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '2348985393', '5번 질문입니다.', '5번 질문 내용입니다.', '2022-03-05');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '3', '6번 질문입니다.', '6번 질문 내용입니다.', '2022-03-06');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, 'sk', '7번 질문입니다.', '7번 질문 내용입니다.', '2022-03-07');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, NULL, 0, '3', '8번 질문입니다.', '8번 질문 내용입니다.', '2022-03-08');

INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 0, 1, 'admin', '1번 질문 답글입니다.', '1번 질문 답글 내용입니다.', '2022-03-09');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 0, 1, 'admin', '1번 질문 답글2입니다.', '1번 질문 답글2 내용입니다.', '2022-03-10');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 1, 1, 'admin', '2번 질문 답글입니다.', '2번 질문 답글 내용입니다.', '2022-03-11');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 2, 1, 'admin', '3번 질문 답글입니다.', '3번 질문 답글 내용입니다.', '2022-03-12');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 3, 1, 'admin', '4번 질문 답글입니다.', '4번 질문 답글 내용입니다.', '2022-03-13');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 5, 1, 'admin', '6번 질문 답글입니다.', '6번 질문 답글 내용입니다.', '2022-03-14');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 7, 1, 'admin', '8번 질문 답글입니다.', '8번 질문 답글 내용입니다.', '2022-03-15');


INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 11, 2, '3', '3번 질문 답글의 답글입니다.', '3번 질문 답글의 답글 내용입니다.', '2022-03-16');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 11, 2, '2348985393', '3번 질문 답글의 답글2입니다.', '3번 질문 답글의 답글2 내용입니다.', '2022-03-17');
INSERT INTO &1.BOARD(BOARD_SEQ, BOARD_TYPE, SUPER_BOARD_SEQ, TAB_CNT, WRITER, TITLE, CONTENT, REG_DATE) 
VALUES(&1.SEQ_BOARD.NEXTVAL, 2, 14, 2, '2348985393', '8번 질문 답글의 답글입니다.', '8번 질문 답글의 답글 내용입니다.', '2022-03-18');
