DROP TABLE &1.GOODS;

CREATE TABLE &1.GOODS(
    CODE            NUMBER(3)    CONSTRAINT PK_MEMBER PRIMARY KEY,
    PASSWORD        VARCHAR2(20),
    NAME            VARCHAR2(30)    NOT NULL,
    PHONE           VARCHAR2(11)    CONSTRAINT UK_MEMBER_PHONE UNIQUE,
    EMAIL           VARCHAR2(40),
    BASIC_ADDR      VARCHAR2(100),
    DETAIL_ADDR     VARCHAR2(100),
    POST            VARCHAR2(6),
    TYPE            CHAR(1)         DEFAULT 'U' CONSTRAINT CK_MEMBER_TYPE CHECK (TYPE IN ('S', 'U')), 
    REG_DATE        DATE            DEFAULT SYSDATE
);