drop function FC_DELETE_BOARD;
CREATE OR REPLACE PROCEDURE PR_DELETE_BOARD(
    V_BOARD_SEQ BOARD.BOARD_SEQ%TYPE
)
AS
BEGIN
    DELETE FROM BOARD WHERE BOARD_SEQ = V_BOARD_SEQ;
    COMMIT;
    
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
END;
/

select * from board;