CREATE OR REPLACE FUNCTION FC_GET_ACCOUNT_PASSWORD(
    V_ACCOUNT_NO    VARCHAR2
)
RETURN VARCHAR2
AS
    V_PASSWORD_CK   VARCHAR2(20);
BEGIN
    SELECT PASSWORD INTO V_PASSWORD_CK FROM ACCOUNT WHERE ACCOUNT_NO = V_ACCOUNT_NO;
    RETURN V_PASSWORD_CK;
END;
/
VARIABLE RES VARCHAR2(20);
EXEC :RES := FC_GET_ACCOUNT_PASSWORD(13900000000001);
PRINT :RES;