REM EXCEPTION을 기록하는 WITE_LOG_PROCEDURE 생성 + AUTONOMOUS TRAMSACTION
CREATE OR REPLACE PROCEDURE
    WRITE_LOG(A_PROGRAM_NAME IN VARCHAR2, A_ERROR_MESSAGE IN VARCHAR2, A_DESCRIPTION IN VARCHAR2)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    -- EXCEPTION을 LOG테이블에 기록
    INSERT INTO EXCEPTION_LOG(PROGRAM_NAME, ERROR_MESSAGE, DESCRIPTION)
    VALUES(A_PROGRAM_NAME, A_ERROR_MESSAGE, A_DESCRIPTION);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
